# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Tests

on:
    pull_request:
        branches: [main, development, feat/**]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [24.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                redis-version: [6]

        steps:
            - uses: actions/checkout@v5

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v5
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Redis Server in GitHub Actions
              uses: supercharge/redis-github-action@1.8.1
              with:
                  redis-version: ${{ matrix.redis-version }}

            - run: pnpm install --frozen-lockfile
            - run: pnpm build --if-present
            - run: pnpm test
